import assert from 'node:assert/strict';
import {FightEngine} from '../dist/engine.js';
import {ROSTER,RULES} from '../dist/roster.js';
let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name)}
function setup(id=0,opponent=3){const e=new FightEngine(()=>.5);e.start(id,opponent);e.phase='fight';e.ai=()=>({});return e}
function advance(e,seconds,input={}){for(let i=0;i<seconds*120;i++)e.update(1/120,input)}
test('countdown, bounded movement, jump lands',()=>{const e=new FightEngine();e.start(0,2);advance(e,2.6);assert.equal(e.phase,'fight');e.ai=()=>({});const f=e.fighters[0];advance(e,.1,{jump:true});assert(f.y<RULES.floor);advance(e,1);assert.equal(f.y,RULES.floor);advance(e,5,{move:-1});assert.equal(f.x,RULES.left)});
test('punch hits once with startup and recovery; far punches miss',()=>{const e=setup(),[f,o]=e.fighters;o.x=f.x+100;assert(e.tryAttack(f,'punch'));advance(e,.04);assert.equal(o.hp,o.data.hp);advance(e,.32);assert(o.hp<o.data.hp);const hp=o.hp;advance(e,.8);assert.equal(hp,o.hp);o.x=1100;assert(e.tryAttack(f,'kick'));advance(e,1);assert.equal(hp,o.hp)});
test('front block reduces damage and guard can break',()=>{const e=setup(),[f,o]=e.fighters;o.x=f.x+100;o.dir=-1;o.blocking=true;const hp=o.hp;e.hit(f,o,100);const blocked=hp-o.hp;assert(blocked<30);o.invul=0;o.blocking=false;o.stun=0;e.hit(f,o,100);assert(hp-o.hp>100);o.invul=0;o.blocking=true;o.guard=5;e.hit(f,o,100);assert(o.guardBreak>0)});
test('energy requirements, cooldown, maximum energy',()=>{const e=setup(),f=e.fighters[0];f.energy=24;assert(!e.tryAttack(f,'special'));f.energy=25;assert(e.tryAttack(f,'special'));assert.equal(f.energy,0);advance(e,1);assert(f.summon>0);f.energy=100;assert(!e.tryAttack(f,'special'));assert(e.tryAttack(f,'ultimate'));assert.equal(f.energy,0);advance(e,30);assert(f.energy<=100)});
test('all eight specials have their specified gameplay effects',()=>{for(let id=0;id<8;id++){const e=setup(id),[f,o]=e.fighters;o.x=f.x+180;const hp=o.hp;f.energy=100;assert(e.tryAttack(f,'special'));advance(e,1.8);if(id===0)assert(f.summon>0);else if(id===7)assert(f.shield>0);else assert(o.hp<hp,ROSTER[id].id+' special should damage');if(id===4)assert(o.slow>0);if(id===3)assert(o.burn>0);if(id===6)assert(f.x>o.x)}});
test('all eight ultimates consume full meter and damage reachable opponent',()=>{for(let id=0;id<8;id++){const e=setup(id),[f,o]=e.fighters;o.x=f.x+150;f.energy=100;assert(e.tryAttack(f,'ultimate'));assert.equal(f.energy,0);advance(e,2);assert(o.hp<o.data.hp,ROSTER[id].id+' ultimate should damage')}});
test('jump avoids ground shockwaves',()=>{const e=setup(2),[f,o]=e.fighters;o.x=f.x+250;o.y=RULES.floor-200;o.vy=-400;e.projectile(f,{damage:100,ground:true,y:RULES.floor-15,speed:700});advance(e,.25);assert.equal(o.hp,o.data.hp)});
test('shield mitigates hits; burn and slow expire',()=>{const e=setup(),[f,o]=e.fighters;o.shield=4;const hp=o.hp;e.hit(f,o,100,{status:'slow'});assert(hp-o.hp<50);assert(o.slow>0);advance(e,3);assert.equal(o.slow,0);o.burn=.1;advance(e,.2);assert.equal(o.burn,0)});
test('combo increases and expires',()=>{const e=setup(),[f,o]=e.fighters;e.hit(f,o,40);o.invul=0;e.hit(f,o,40);assert.equal(f.combo,2);advance(e,1);assert.equal(f.combo,0)});
test('pause preserves physics and timer',()=>{const e=setup();e.pause();const before=e.snapshot();advance(e,5,{move:1});assert.deepEqual(e.snapshot(),before);e.resume();advance(e,.1);assert(e.time<before.time)});
test('KO, best of three, rematch, time ratio and draw',()=>{const e=setup();e.fighters[1].hp=0;advance(e,.02);assert.equal(e.phase,'roundEnd');assert.equal(e.wins[0],1);e.nextRound();e.phase='fight';e.fighters[1].hp=0;advance(e,.02);assert.equal(e.phase,'matchEnd');assert.equal(e.wins[0],2);e.nextRound();assert.deepEqual(e.wins,[0,0]);e.phase='fight';e.time=0;e.fighters[0].hp=e.fighters[0].data.hp*.5;e.fighters[1].hp=e.fighters[1].data.hp*.5;advance(e,.02);assert.equal(e.result.winner,null);assert.deepEqual(e.wins,[0,0])});
test('AI survives 24 representative fights without invalid states',()=>{for(const diff of ['easy','normal','hard'])for(let id=0;id<8;id++){const e=new FightEngine(()=>.53);e.start(id,(id+3)%8,diff);advance(e,25,{move:1,attack:'punch'});for(const f of e.fighters)for(const key of ['x','y','hp','energy'])assert(Number.isFinite(f[key]));assert(e.fighters.every(f=>f.hp>=0&&f.energy<=100))}});
test('invalid fighter and difficulty fail intentionally',()=>{assert.throws(()=>new FightEngine().start(99,0));assert.throws(()=>new FightEngine().start(0,0,'invalid'))});
console.log(passed+' combat checks passed');

